pre_setup: draw_kinematic_chain

spawn_config:
  teams:
    -
      name: Red
      color: [255, 0, 0]
      controller: 
        type: Wasm
        reload: true
        path: "<no path specified>"

  spawns:
    -
      x: 0.0
      y: 0.0
      yaw: 0.0
      team: 0
      unit: Arm
      controller:
        type: TeamController
        name: Red
