[package]
name = "cgmath_util"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]

cgmath = {version = "0.18.0", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
