[package]
name = "implementation_module"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.16.0"

[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
